site_url = ""
site_name = "My Week"
site_motto = "guapodero"
footer_note = "life is a gift"
media_dir = "media"
build_dir = "_build"
theme = "myweek"
theme_root_dir = "_themes"
rebuild_interval = 2
posts_per_page = 20
